- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.agignore:
    ~/.dotfiles: ''
    ~/.ipython/profile_default/ipython_kernel_config.py:
    ~/.gitconfig:
    ~/.gitignore_global:
    ~/.gnupg/gpg.conf:
    ~/.inputrc:
    ~/.screenrc:
    ~/.tmux.conf:
    ~/.vim:
    ~/.vimrc:
    ~/.zshrc:
    ~/.emacs.d: emacs.d

- shell:
  - git update-submodules # after linking ~/.gitconfig
